usadellab/GeneExpressionPlots

src/components/AppPlot.jsx, src/layout/AppLayout.jsx, src/modules/data/components/GroupItem.jsx, src/modules/data/layout/DataLayout.jsx, src/modules/data/pages/DataView.jsx, src/modules/plotly/layout/PlotsLayout.jsx, src/modules/plotly/pages/PlotsView.jsx, src/utils/plotsHelper.js
Closes #23.
This PR makes the image and plot elements resizable on the horizontal axis.
- Image and plot containers use the CSS `resize` property.
- Plots are instructed to resize via the `ResizeObserver` API.
- Plots use the `autosize` and `responsive` properties to adjust their dimensions on container and window resize events, respectively.
- Plots layout as a flex-wrap container.
- Image and plots are resizable on the horizontal axis and have a default full-width in the initial render.
- A grey background has been added to the main layout, to better highlight data, image, and plot cards
- The `ResizeObserver` API is supported in most modern browsers, but it won't work in Internet Explorer (any version). More information in [caniuse](https://caniuse.com/resizeobserver),
- This PR likely …
=> Feat resizable plots

src/assets/svg/hero-icons.svg, src/components/AppModal2.jsx, src/components/AppOverlay.jsx, src/modules/tools/components/GeneDetails.jsx, src/modules/tools/pages/GeneBrowser.jsx, tailwind.config.js
None yet.
This PR adds a new **Gene Browser** modal window that shows detailed _data_ information about the currently selected gene.
- Added `tailwindcss` variants to support `first`, `odd`, and `group-hover` modifiers necessary for the new component.
- Tweaked the `AppModal` component header to better complement its size and positioning with different screens and sibling components.
- Added a root `className` property to the `AppModal` component.
- Improved height-width response of the modal to different screen sizes.
- Add a new `GeneDetails.jsx` component to how selected gene data information. This component is displayed within a modal controlled in `GeneBrowser.jsx`.
- Header row should be fixed at the top of the Gene Details modal window.
- The AppModal2 component should be …
=> feat: gene browser details window

src/components/cards/GeneCard.jsx, src/modules/plotly/components/PlotCaption.jsx, src/modules/plotly/components/PlotlyPlot.jsx, src/modules/plotly/pages/PlotsView.jsx, src/modules/tools/components/GeneDetails.jsx, src/modules/tools/pages/GeneBrowser.jsx
This PR addresses layout fixes for the gene information (gene-card component) used in figure captions and the gene-browser tool.
- Add a new `gene-card` component that can be re-used in captions and the gene-browser.
- Use a flex layout to align each info property with this value or description.
- Fix the plot-caption not having an accession-based key.
- Various color and display changes to the gene-cards displayed in captions.
=> feat: gene card

cypress/plugins/index.ts, cypress/tests/components/AppAnchor.test.tsx, cypress/tests/integration/enrichment.test.ts, cypress/tests/integration/heatmap.test.ts, cypress/tsconfig.json, cypress/webpack.config.ts, package.json, yarn.lock
This PR adds alias support to cypress tests.
- Add a custom `webpack.config.ts` that is loaded in `plugins` via the `@cypress/webpack-preprocessor` package.
=> tests: support path aliases in cypress tests

.eslintignore, index.html, package.json, postcss.config.js, src/modules/plotly/components/PlotlyPlot.jsx, src/store/plot-store.js, src/utils/plotsHelper.js, vite.config.js, yarn.lock
This PR removes the `plotly.js` CDN dependency and updates the `PlotlyPlot` component to work without importing `plotly.js`.
- Remove the `plotly.js` CDN script tag.
- Update the `PlotlyPlot` component to not rely on Plotly for plot resizing due to compilation problems. The `ResizeObserver` API is still used, but only to update the layout (trigger a plot re-render) on resize events.
- Fix several leftover linter warnings in config files.
=> chore: use plotly from npm

src/components/formik-field/formik-field.tsx, src/components/formik-switch/formik-switch.tsx, src/components/formik-switch/index.tsx, src/pages/plots/components/bars-form.tsx, src/pages/plots/plots-home.tsx
This PR adds functionality to the **Bars Plot** sidebar menu in `plots-home` to open a new `bars-form` component implementing a subset of the old **New Plot** menu. The new form implements a formik array field to input accessions.
- Add support for left and right addon and element children in `formik-field`.
- Add a new `formik-switch` component that integrates `formik` with `chakra-ui`'s `switch` component.
- Add a new `bars-form` component with all necessary inputs to create a bars plot. In this component, accession inputs are implemented using `formik`'s `ArrayField`.
- Add functionality to the **Bars Plot** sidebar menu so that now it opens the `bars-form` within a modal.
=> feat: bars form and formik arrray

src/css/plotly.css, src/pages/plots/components/PlotlyPlot.tsx, src/pages/plots/components/heatmap-plot.tsx, src/pages/plots/components/plot-container.tsx, src/pages/plots/plots-home.tsx
This PR implements the plot-container for PlotlyPlot component as well as moving the title to the plot-container instead of using plotly to set the title.
- refactor: use plot-container for plotly plots
- refactor: plot-container to display plot-title as h1
- fix: warning to cleanup ref in resizePlot useEffect
- fix: heatmap padding not a property value in firefox
=> refactor: use plot-container for plotly plots

src/components/formik-accession/formik-accession.tsx, src/components/formik-accession/index.tsx, src/hooks/index.ts, src/hooks/match-accesion.ts, src/pages/plots/components/bars-form.tsx, src/pages/plots/components/heatmap-plot.tsx, src/pages/plots/components/individual-lines-form.tsx, src/pages/plots/components/stacked-lines-form.tsx
This PR adds autocompletion to accession inputs in bars and line plots.
- Add new `useMatchAccession` hook.
- Add new `formik-accession` input component`.
- Replace `formik-field` with `formik-accession` in bars and lines plots.
- Ignore the left axis to heatmap re-commit. It's been a long day and I don't want to deal with that...
=> feat: accession autocomplete

src/pages/plots/plots-home.tsx
This PR makes three small modifications to the plots page sidebar:
- Position the sidebar as a fixed element in the page, so it does not trigger layout changes when expanding the menus.
- Replace the experimental text-icons with real SVG icons, as appropriate as possible using `react-icons` resources.
- Add a new **Remove Plots** menu button that clears all the existing plots in the plot store.
=> feat: plots sidebar layout, icons, and delete functionality

src/app-routes.tsx, src/components/link-card/index.ts, src/components/link-card/link-card.tsx, src/pages/info/info-home.tsx, src/pages/info/info-routes.tsx
This PR adds documentation content to the info route. For now a collection of link cards that refer to the appropriate github pages.
- Add a new `link-card` component similar in style to the `nav-link`.
- Add a new `info-page` and integrate in the application routes.
=> feat: Info routes

src/app-home.tsx, src/app-routes.tsx, src/components/nav-sidebar/sidebar-button.tsx, src/components/nav-sidebar/sidebar-nav.tsx, src/components/nav-topbar/topbar-link.tsx, src/layouts/app-layout/app-layout.tsx, src/pages/data/data-files.tsx, src/pages/data/data-routes.tsx, src/pages/plots/plots-home.tsx, src/pages/tools/components/gene-browser.tsx
This PR implements several tweaks and fixes to page layouts and UI flow mechanisms.
- Remove the `data-home` page from the router and load `data-files` instead.
- Remove the empty home page and load the `data-files` page instead.
- Disable buttons in the sidebar actions of `data-files` and `plots-home`, as appropriate.
- Warn the user when in the `plots-home` page and no data has been loaded.
- Warn the user when in the `gene-browser` page and no data has been loaded.
- Prevent the text of the application navigation bar buttons from being selected (it was causing mis-navigation events).
- Fix the now floating actions sidebar in `plots-home` from being selectable when a modal is open.
=> feat: app layout and flow tweaks

src/pages/plots/components/bars-form.tsx, src/pages/plots/components/individual-lines-form.tsx, src/pages/plots/components/stacked-lines-form.tsx
This PR adds a validation step to plot accession inputs, to verify that the current accession exists in the database. Additionally, it disables input validation `onBlur`, as it was causing UX issues when trying to cancel the form.
- Add an additional validation check to `validateAccession`.
- Set `validateOnBlur` to `false` in plot forms that did not have it.
=> feat: accession validation

src/pages/data/components/export-form.tsx, src/pages/data/components/import-form.tsx, src/pages/data/components/info-form.tsx, src/pages/data/components/xtable-form.tsx
This PR adds missing `validateOnBlur={false}` to data forms to fix being able to cancel without triggering validation.
=> fix: missing validateOnBlur for data forms

src/components/formik-radio/formik-radio.tsx, src/components/formik-radio/index.ts, src/pages/plots/components/stacked-lines-form.tsx, src/pages/plots/plots-home.tsx, src/utils/plots/stacked-lines.ts
This PR implements the colorBy `group` or `accession` feature for stacked line plots
- add generic reusable `form-radio` component
- use the component in the stacked-lines form
=> feat: color by for stacked lines form

src/app.tsx, src/layouts/app-layout/app-layout.tsx, src/utils/fetch.ts
This PR adds application state handling to the preload functionality.
- When preloading, display a loading indicator and message.
- If preloading fails at _any_ step, override routes with a custom error message.
- Change `fetchResource` so it no longer returns undefined on a not-ok response. Now the helper will always return the appropriate value or throw the relevant error.
- Change `AppLayout` props to extend `FlexProps` from `chakra-ui`. This allows overriding styles for slightly different layout requirements.
- Add application state to reflect the current preloading status: `idle`, `loading`, `failed`.
=> feat: app state

src/hooks/match-accesion.ts
This PR is a small optimization to useMatchAccession so it only searches the database when the accession value changes and is not undefined.
=> hotfix: optimize accession matching

src/components/formik-radio/formik-radio.tsx, src/components/formik-replicate/formik-replicate.tsx, src/components/formik-replicate/index.tsx, src/hooks/index.ts, src/hooks/match-replicate.ts, src/pages/plots/components/heatmap-form.tsx, src/pages/plots/plots-home.tsx, src/store/plot-store.ts, src/types/plots.ts, src/utils/plots/heatmap.ts, src/utils/store.ts, src/workers/heatmap.ts
This PR enables support to transpose the input matrix for the Heatmap plot. This enables us to cluster replicates as well as genes by their measure of likeness.
Furthermore added support to use only a subset of genes for the Heatmap plot.
- refactor: formik-radio optional disable prop
- feat: match-replicate hook
- feat: formik replicate component
- feat: heatmap add optional gene filter and transpose option
- refactor: plot-sidebar rename heatmap -> cluster heatmap
- fix: add default empty array for row-filter
=> feat: Heatmap transpose matrix + filter for genes

src/pages/plots/components/pca-form.tsx, src/pages/plots/plots-home.tsx, src/store/plot-store.ts, src/types/plots.ts, src/utils/color.ts, src/utils/plots/pca.ts, src/workers/pca.ts
This PR enables support to transpose the input matrix for the PCA plot. This enables us to analyize replicates as well as genes.
Furthermore added support to use only a subset of genes and/or replicates for the PCA plot.
- feat: pca add optional gene/replicate filter and transpose option
- feat: add generic getColors method
=> feat: pca transpose matrix + filter genes/replicates

src/pages/data/data-files.tsx
This PR implements the loading buffer when exporting a GXP database
fix: use await syntax for export. enables the form to render the loading buffer and wait for the export to finish.
Since exporting (the same goes for importing) are `async` they are actually non-blocking. You are able to leave the export/import form. If you do react will give a warning of a non-op, since it tries to set the loading state to false for a Form that is not there anymore.
=> fix: loading buffer for exporting GXP database

src/pages/plots/components/bars-form.tsx, src/pages/plots/components/heatmap-form.tsx, src/pages/plots/components/individual-lines-form.tsx, src/pages/plots/components/pca-form.tsx, src/pages/plots/components/stacked-lines-form.tsx, src/pages/plots/plots-home.tsx, src/pages/tools/tools-home.tsx
- bars plot -> bar plot
- is a tool” or “provides tools to”. GeneBrowser
- accession -> identifier in plot forms
=> fix: typos, labels

src/pages/plots/components/mapman-plot.tsx, src/pages/plots/plots-home.tsx, src/store/plot-store.ts, src/types/plots.ts, src/utils/plots/mapman.ts
This PR implements a refactor on how we render the mapman plots. Instead of recalculating and re-parsing the xml (e.g. when changing pages), the calculation is done separately once when submitting the form. We return an array of rectangles that can directly be bound as data to the svg via d3.
- feat: add mapman util; returns rects + stats
- feat: async action in plot-store to push the plot
- feat: add setTimeOut + async to mapmanformsubmit
- feat: add loading temp plot
- refactor: switch adjust box size buttons
=> Mapman plot refactor

src/pages/plots/components/mapman-form.tsx, src/pages/tools/components/mapman-tool.tsx, src/store/dataframe.ts, src/utils/validation.ts
Added check for numeric columns: checks first ten rows (if available), allow for scientific notation (1.3e-12) and allow different "NA" values (   'na', 'NA', 'N/A', 'n/a', null, NaN,  'NaN',  'nan',  'null', '') ignore those cells
=> refactor: Add validation for Numeric column, Add numeric validation function to dataframe, Update Mapman form pass numeric column validation

src/components/gene-card/gene-card.tsx, src/pages/data/data-files.tsx, src/pages/plots/components/color-legend.tsx, src/pages/plots/components/heatmap-plot.tsx, src/pages/plots/components/mapman-form.tsx, src/pages/plots/components/mapman-plot.tsx, src/pages/plots/plots-home.tsx, src/pages/tools/components/gene-browser-card.tsx, src/pages/tools/components/mapman-tool.tsx, src/store/plot-store.ts, src/types/plots.ts, src/utils/mercator.ts, src/utils/plots/mapman.ts
This PR implements Todos from the meeting on Nov 18. Namely:
- Make import of Mercator table to the data section
- add an eye icon to the gene browser cards to help the user to open the expression count table
- add a link to the gene browser to the data menu
- add a color legend to the MapMan plots
```
refactor: heatmap legend to color legend
- pass x,y values
- feat: add reverse prop to colorlegend
feat: add mercator input load to sidebar
feat: add genebrowser link to sidebar
feat: add dividers to plot sidebar
refactor: add mercator util for parsing
feat: add eyeIcon for detailed tabular view
feat: mapman-plot pass width/height as props
feat: add color-legend to mapman plot
feat: mapman plotTitle prop
fix: reverse heatmap colors / legend
fix: word-break gene caption
```
=> feat: Todos 18 nov

cypress/support/commands.ts, cypress/tests/integration/enrichment.test.ts, src/store/enrichment-store.ts, src/types/enrichment.ts, src/utils/enrichment_analysis.ts, src/utils/fishers-exact-test.ts, src/workers/enrichment.ts
This PR implements some optimizations and refactoring  for the enrichment analysis code.
- fix: a bug were we requested the gsl wasm for each matrix extremefication step. Having too many requests crashed the app
- refactor: Calculate trait A pos/neg gene ids before running the analysis. This enables in case of "multinomial" analysis to only run the enrichment test for those trait A positive genes.
- refactor: no longer convert the dataframe to 2d array
- refactor: separate the calculation of the contingency tables out. This enables us to calculated them separately and pass to the enrichment function.
**Note:** With the current setup, in theory it would be pretty straight forward to implement subworkers for the enrichment worker to further optimize the calculations.
=> refactor: enrichment analysis optimizaion

src/components/formik-area/formik-area.tsx, src/pages/plots/components/plot-container.tsx, src/pages/tools/components/enrichment-form.tsx, src/pages/tools/components/enrichment-tool.tsx, src/store/enrichment-store.ts, src/types/enrichment.ts, src/workers/enrichment.ts
This PR implements the functionality to optionally, instead of filtering for a specific condition in an info-table column, filter for a list a gene identifiers.
Additionally added functionality to download an enrichment-analysis directly as csv from the UI.
- feat: add Tooltip to FormikArea
- fix: correctly import saveAs
- chore: remove debug logs
- feat: funcionality for passing a list of genes to filter
- feat: catch dupliacte enrichment error and show toast notification
- feat: add button to download enrichmnet as CSV
=> feat: enrichment filter option

src/pages/plots/components/bars-form.tsx, src/pages/plots/components/heatmap-form.tsx, src/pages/plots/components/individual-lines-form.tsx, src/pages/plots/components/pca-form.tsx, src/pages/plots/components/stacked-lines-form.tsx
Changes
*  "Gene Identifier 1*"  label in stacked-line, bars and  individual lines forms changed to "(gene/metabolite/accession)" 
*  "The accession ID" does not exist label in stacked-line, bars and individual lines forms changed to "the identifier does not exist" 
*  " List your gene identifiers here, separated by a newline." placeholder in PCA and heatmap form to "List your identifiers here, separated by a newline."
=> refactor: Gene Identifier labels and placeholder in the plots forms
